package client

import (
	"fmt"

	"github.com/privacybydesign/irmago/common/clientmodels"
	"github.com/privacybydesign/irmago/irma"
	"github.com/privacybydesign/irmago/irma/irmaclient"
)

// irmaSessionAdapter adapts the session struct to the irmaclient.Handler interface.
type irmaSessionAdapter struct {
	session *session
}

func (a *irmaSessionAdapter) StatusUpdate(action irma.Action, status irma.ClientStatus) {}

func (a *irmaSessionAdapter) ClientReturnURLSet(clientReturnURL string) {
	a.session.State.ClientReturnUrl = clientReturnURL
	a.session.dispatchState()
}

func (a *irmaSessionAdapter) PairingRequired(pairingCode string) {
	a.session.State.Status = clientmodels.Status_ShowPairingCode
	a.session.State.PairingCode = pairingCode
	a.session.dispatchState()
}

func (a *irmaSessionAdapter) Success(result string) {
	a.session.State.Status = clientmodels.Status_Success
	a.session.dispatchState()
}

func (a *irmaSessionAdapter) Cancelled() {
	a.session.State.Status = clientmodels.Status_Dismissed
	a.session.dispatchState()
}

func (a *irmaSessionAdapter) Failure(err *irma.SessionError) {
	a.session.error(err)
}

func (a *irmaSessionAdapter) KeyshareBlocked(manager irma.SchemeManagerIdentifier, duration int) {
	a.session.State.PinBlockedTimeSeconds = &duration
	a.session.State.Status = clientmodels.Status_RequestPin
	a.session.dispatchState()
}

func (a *irmaSessionAdapter) KeyshareEnrollmentMissing(manager irma.SchemeManagerIdentifier) {
	a.session.error(fmt.Errorf("keyshare enrollment is missing for scheme: '%s'", manager))
}

func (a *irmaSessionAdapter) RequestIssuancePermission(
	request *irma.IssuanceRequest,
	satisfiable bool,
	candidates [][]irmaclient.DisclosureCandidates,
	requestorInfo *irma.RequestorInfo,
	callback irmaclient.PermissionHandler,
) {
	s := a.session

	// if the session type wasn't an issuance session before
	// we can assume this session to be chained and we can cache that for future permission requests
	if s.State.Type != "" && s.State.Type != clientmodels.Type_Issuance {
		s.chained = true
	}

	irmaConfig := s.client.irmaClient.Configuration
	creds := request.CredentialInfoList

	offeredCredentials, err := credentialInfoListToSchemaless(irmaConfig, creds)
	if err != nil {
		s.error(err)
		return
	}

	credentials, err := s.client.GetCredentials()
	if err != nil {
		s.error(err)
		return
	}

	// if the session is a chained session and the previous type was disclosure or signature
	// we don't want to update the disclosure plan and instead make a new one
	// if the current (issuance) session has any disclosures
	if s.chained && s.State.Type != clientmodels.Type_Issuance {
		s.State.DisclosurePlan = nil
	} else {
		s.snapshotPreExistingCredentials(credentials)
		newPlan, err := createDisclosurePlan(s.State.DisclosurePlan, irmaConfig, credentials, candidates, s.preExistingCredentialHashes)
		if err != nil {
			s.error(err)
			return
		}

		s.State.DisclosurePlan = newPlan
	}

	// Filter out random blind attributes from offered credentials,
	// as they are generated by the protocol and not meaningful to the user during issuance permission.
	filterRandomBlindAttributes(irmaConfig, offeredCredentials)

	s.State.OfferedCredentials = offeredCredentials
	s.State.Status = clientmodels.Status_RequestPermission
	s.permissionHandler = callback
	s.State.Protocol = clientmodels.Protocol_Irma
	s.State.Requestor = requestorInfoToTrustedParty(requestorInfo)
	s.State.Type = clientmodels.Type_Issuance

	s.dispatchState()
}

func (a *irmaSessionAdapter) RequestVerificationPermission(
	request *irma.DisclosureRequest,
	satisfiable bool,
	candidates [][]irmaclient.DisclosureCandidates,
	requestorInfo *irma.RequestorInfo,
	callback irmaclient.PermissionHandler,
) {
	s := a.session

	s.State.Status = clientmodels.Status_RequestPermission
	s.State.Type = clientmodels.Type_Disclosure
	s.permissionHandler = callback
	s.State.Requestor = requestorInfoToTrustedParty(requestorInfo)
	s.State.OfferedCredentials = nil

	creds, err := s.client.GetCredentials()
	if err != nil {
		s.error(err)
		return
	}

	s.snapshotPreExistingCredentials(creds)
	newPlan, err := createDisclosurePlan(s.State.DisclosurePlan, s.client.irmaClient.Configuration, creds, candidates, s.preExistingCredentialHashes)
	if err != nil {
		s.error(err)
		return
	}

	s.State.DisclosurePlan = newPlan
	s.dispatchState()
}

func (a *irmaSessionAdapter) RequestSignaturePermission(
	request *irma.SignatureRequest,
	satisfiable bool,
	candidates [][]irmaclient.DisclosureCandidates,
	requestorInfo *irma.RequestorInfo,
	callback irmaclient.PermissionHandler,
) {
	s := a.session

	s.State.Status = clientmodels.Status_RequestPermission
	s.State.Type = clientmodels.Type_Signature
	s.State.Requestor = requestorInfoToTrustedParty(requestorInfo)
	s.permissionHandler = callback
	s.State.OfferedCredentials = nil

	creds, err := s.client.GetCredentials()
	if err != nil {
		s.error(err)
		return
	}

	s.snapshotPreExistingCredentials(creds)
	newPlan, err := createDisclosurePlan(s.State.DisclosurePlan, s.client.irmaClient.Configuration, creds, candidates, s.preExistingCredentialHashes)
	if err != nil {
		s.error(err)
		return
	}

	s.State.DisclosurePlan = newPlan
	s.State.MessageToSign = request.Message

	s.dispatchState()
}

func (a *irmaSessionAdapter) RequestPin(remainingAttempts int, callback irmaclient.PinHandler) {
	s := a.session
	s.State.Status = clientmodels.Status_RequestPin
	if remainingAttempts >= 0 {
		s.State.RemainingPinAttempts = &remainingAttempts
	} else {
		s.State.RemainingPinAttempts = nil
	}
	s.pinHandler = callback
	s.dispatchState()
}
