package client

import (
	"fmt"
	"time"

	"github.com/privacybydesign/irmago/common/clientmodels"
	"github.com/privacybydesign/irmago/irma"
	"github.com/privacybydesign/irmago/irma/irmaclient"
)

// irmaSessionAdapter adapts the session struct to the irmaclient.Handler interface.
type irmaSessionAdapter struct {
	session *session
}

func (a *irmaSessionAdapter) StatusUpdate(action irma.Action, status irma.ClientStatus) {}

func (a *irmaSessionAdapter) ClientReturnURLSet(clientReturnURL string) {
	a.session.State.ClientReturnUrl = clientReturnURL
	a.session.dispatchState()
}

func (a *irmaSessionAdapter) PairingRequired(pairingCode string) {
	a.session.State.Status = clientmodels.Status_ShowPairingCode
	a.session.State.PairingCode = pairingCode
	a.session.dispatchState()
}

func (a *irmaSessionAdapter) Success(result string) {
	a.session.State.Status = clientmodels.Status_Success
	a.session.dispatchState()
}

func (a *irmaSessionAdapter) Cancelled() {
	a.session.State.Status = clientmodels.Status_Dismissed
	a.session.dispatchState()
}

func (a *irmaSessionAdapter) Failure(err *irma.SessionError) {
	a.session.error(err)
}

func (a *irmaSessionAdapter) KeyshareBlocked(manager irma.SchemeManagerIdentifier, duration int) {
	a.session.State.PinBlockedTimeSeconds = &duration
	a.session.State.Status = clientmodels.Status_RequestPin
	a.session.dispatchState()
}

func (a *irmaSessionAdapter) KeyshareEnrollmentMissing(manager irma.SchemeManagerIdentifier) {
	a.session.error(fmt.Errorf("keyshare enrollment is missing for scheme: '%s'", manager))
}

func (a *irmaSessionAdapter) RequestIssuancePermission(
	request *irma.IssuanceRequest,
	satisfiable bool,
	candidates [][]irmaclient.DisclosureCandidates,
	requestorInfo *irma.RequestorInfo,
	callback irmaclient.PermissionHandler,
) {
	s := a.session

	// if the session type wasn't an issuance session before
	// we can assume this session to be chained and we can cache that for future permission requests
	if s.State.Type != "" && s.State.Type != clientmodels.Type_Issuance {
		s.chained = true
	}

	irmaConfig := s.client.irmaClient.Configuration
	creds := request.CredentialInfoList

	offeredCredentials, err := credentialInfoListToSchemaless(irmaConfig, creds)
	if err != nil {
		s.error(err)
		return
	}

	credentials, err := s.client.GetCredentials()
	if err != nil {
		s.error(err)
		return
	}

	// if the session is a chained session and the previous type was disclosure or signature
	// we don't want to update the disclosure plan and instead make a new one
	// if the current (issuance) session has any disclosures
	if s.chained && s.State.Type != clientmodels.Type_Issuance {
		s.State.DisclosurePlan = nil
	} else {
		s.snapshotPreExistingCredentials(credentials)
		newPlan, err := createDisclosurePlan(s.State.DisclosurePlan, irmaConfig, credentials, candidates, s.preExistingCredentialHashes)
		if err != nil {
			s.error(err)
			return
		}

		s.State.DisclosurePlan = newPlan
	}

	// Filter out random blind attributes from offered credentials,
	// as they are generated by the protocol and not meaningful to the user during issuance permission.
	filterRandomBlindAttributes(irmaConfig, offeredCredentials)

	s.State.OfferedCredentials = offeredCredentials
	s.State.Status = clientmodels.Status_RequestPermission
	s.permissionHandler = callback
	s.irmaDiscloseRequest = request.Disclose
	s.State.Protocol = clientmodels.Protocol_Irma
	s.State.Requestor = requestorInfoToTrustedParty(requestorInfo)
	s.State.Type = clientmodels.Type_Issuance

	s.dispatchState()
}

func (a *irmaSessionAdapter) RequestVerificationPermission(
	request *irma.DisclosureRequest,
	satisfiable bool,
	candidates [][]irmaclient.DisclosureCandidates,
	requestorInfo *irma.RequestorInfo,
	callback irmaclient.PermissionHandler,
) {
	s := a.session

	s.State.Status = clientmodels.Status_RequestPermission
	s.State.Type = clientmodels.Type_Disclosure
	s.permissionHandler = callback
	s.irmaDiscloseRequest = request.Disclose
	s.State.Requestor = requestorInfoToTrustedParty(requestorInfo)
	s.State.OfferedCredentials = nil

	creds, err := s.client.GetCredentials()
	if err != nil {
		s.error(err)
		return
	}

	s.snapshotPreExistingCredentials(creds)
	newPlan, err := createDisclosurePlan(s.State.DisclosurePlan, s.client.irmaClient.Configuration, creds, candidates, s.preExistingCredentialHashes)
	if err != nil {
		s.error(err)
		return
	}

	s.State.DisclosurePlan = newPlan
	s.dispatchState()
}

func (a *irmaSessionAdapter) RequestSignaturePermission(
	request *irma.SignatureRequest,
	satisfiable bool,
	candidates [][]irmaclient.DisclosureCandidates,
	requestorInfo *irma.RequestorInfo,
	callback irmaclient.PermissionHandler,
) {
	s := a.session

	s.State.Status = clientmodels.Status_RequestPermission
	s.State.Type = clientmodels.Type_Signature
	s.State.Requestor = requestorInfoToTrustedParty(requestorInfo)
	s.permissionHandler = callback
	s.irmaDiscloseRequest = request.Disclose
	s.State.OfferedCredentials = nil

	creds, err := s.client.GetCredentials()
	if err != nil {
		s.error(err)
		return
	}

	s.snapshotPreExistingCredentials(creds)
	newPlan, err := createDisclosurePlan(s.State.DisclosurePlan, s.client.irmaClient.Configuration, creds, candidates, s.preExistingCredentialHashes)
	if err != nil {
		s.error(err)
		return
	}

	s.State.DisclosurePlan = newPlan
	s.State.MessageToSign = request.Message

	s.dispatchState()
}

func (a *irmaSessionAdapter) RequestPin(remainingAttempts int, callback irmaclient.PinHandler) {
	s := a.session
	s.State.Status = clientmodels.Status_RequestPin
	if remainingAttempts >= 0 {
		s.State.RemainingPinAttempts = &remainingAttempts
	} else {
		s.State.RemainingPinAttempts = nil
	}
	s.pinHandler = callback
	s.dispatchState()
}

func (client *Client) rawLogEntryToLogInfo(entry *irmaclient.LogEntry) (clientmodels.LogInfo, error) {
	// NOTE: iOS builds change the container ID of the app, meaning that after every compilation/app update the location
	// of all app data changes. Logs store an absolute path to requestor logo's, which becomes invalid when the data is moved,
	// resulting in the logo's not being found for existing logs when an iOS app is updated.
	// Solving this issue correctly would require a deep refactor of many components and would likely introduce some very obscure bugs.
	// This hacky solution works around the issue by assuming the image path to be invalid and resolving it based on other information:
	//  - For OpenID4VP sessions the logo path is resolved based on the image name
	//  - For IRMA sessions the logo path is resolved based on the requestor ID and using the requestor schemes
	requestor := entry.ServerName

	if entry.OpenID4VP != nil {
		verifier := requestorInfoToTrustedPartyPtr(requestor)

		if requestor != nil && requestor.Logo != nil {
			verifier.Image = client.openid4vpClient.Configuration.ResolveVerifierLogo(*requestor.Logo)
		}

		return clientmodels.LogInfo{
			Type: clientmodels.LogType_Disclosure,
			Time: time.Time(entry.Time),
			DisclosureLog: &clientmodels.DisclosureLog{
				Protocol:    clientmodels.Protocol_OpenID4VP,
				Credentials: openid4vpCredentialLogsToLogCredentials(client.GetIrmaConfiguration(), entry.OpenID4VP.DisclosedCredentials),
				Verifier:    verifier,
			},
		}, nil
	}

	// resolve the image for an irma session
	if requestor != nil && requestor.Logo != nil {
		requestorScheme, ok := client.GetIrmaConfiguration().RequestorSchemes[requestor.ID.RequestorSchemeIdentifier()]
		if ok && requestorScheme != nil {
			path := requestor.ResolveLogoPath(requestorScheme)
			requestor.LogoPath = &path
		}
	}

	irmaConfig := client.GetIrmaConfiguration()

	switch entry.Type {
	case irma.ActionDisclosing, irma.ActionSigning:
		attributes, err := entry.GetDisclosedCredentials(irmaConfig)
		if err != nil {
			return clientmodels.LogInfo{}, err
		}
		credLog, err := disclosedAttributesToLogCredentials(irmaConfig, attributes)
		if err != nil {
			return clientmodels.LogInfo{}, err
		}
		disclosureLog := &clientmodels.DisclosureLog{
			Protocol:    clientmodels.Protocol_Irma,
			Credentials: credLog,
			Verifier:    requestorInfoToTrustedPartyPtr(requestor),
		}

		if entry.Type == irma.ActionSigning {
			return clientmodels.LogInfo{
				Type: clientmodels.LogType_Signature,
				Time: time.Time(entry.Time),
				SignedMessageLog: &clientmodels.SignedMessageLog{
					Message:       string(entry.SignedMessage),
					DisclosureLog: *disclosureLog,
				},
			}, nil
		}
		return clientmodels.LogInfo{
			Type:          clientmodels.LogType_Disclosure,
			Time:          time.Time(entry.Time),
			DisclosureLog: disclosureLog,
		}, nil

	case irma.ActionIssuing:
		attributes, err := entry.GetDisclosedCredentials(irmaConfig)
		if err != nil {
			return clientmodels.LogInfo{}, err
		}
		credLog, err := disclosedAttributesToLogCredentials(irmaConfig, attributes)
		if err != nil {
			return clientmodels.LogInfo{}, err
		}
		issued, err := entry.GetIssuedCredentials(irmaConfig)
		if err != nil {
			return clientmodels.LogInfo{}, err
		}
		issuedLog, err := issuedCredentialsToLogCredentials(irmaConfig, issued)
		if err != nil {
			return clientmodels.LogInfo{}, err
		}
		return clientmodels.LogInfo{
			Time: time.Time(entry.Time),
			Type: clientmodels.LogType_Issuance,
			IssuanceLog: &clientmodels.IssuanceLog{
				Protocol:             clientmodels.Protocol_Irma,
				Credentials:          issuedLog,
				DisclosedCredentials: credLog,
				Issuer:               requestorInfoToTrustedPartyPtr(requestor),
			},
		}, nil

	case irmaclient.ActionRemoval:
		removedCreds := []clientmodels.LogCredential{}

		for credentialTypeId, attributeValues := range entry.Removed {
			credTypeInfo := irmaConfig.CredentialTypes[credentialTypeId]
			issuer := irmaConfig.Issuers[credTypeInfo.IssuerIdentifier()]

			formats := make([]clientmodels.CredentialFormat, len(entry.RemovedFormats))
			for i, f := range entry.RemovedFormats {
				formats[i] = clientmodels.CredentialFormat(f)
			}

			attributes := []clientmodels.Attribute{}
			for _, atType := range sortedAttributeTypes(credTypeInfo.AttributeTypes) {
				if atType.RevocationAttribute {
					continue
				}
				rawVal := irma.TranslatedString(attributeValues[atType.Index])
				description := clientmodels.TranslatedString(atType.Description)
				name := clientmodels.TranslatedString(atType.Name)
				attributes = append(attributes, clientmodels.Attribute{
					ClaimPath:   []any{atType.ID},
					DisplayName: &name,
					Description: &description,
					Value:       buildAttributeValue(atType.DisplayHint, &rawVal),
				})
			}

			removedCreds = append(removedCreds, clientmodels.LogCredential{
				CredentialId: credentialTypeId.String(),
				Formats:      formats,
				Image:        clientmodels.ImageFromFile(credTypeInfo.Logo(irmaConfig)),
				Name:         clientmodels.TranslatedString(credTypeInfo.Name),
				Issuer: clientmodels.TrustedParty{
					Id:   issuer.Identifier().String(),
					Name: clientmodels.TranslatedString(issuer.Name),
				},
				Attributes: attributes,
				IssueURL:   convertOptionalTranslatedString(credTypeInfo.IssueURL),
			})
		}
		return clientmodels.LogInfo{
			Time: time.Time(entry.Time),
			Type: clientmodels.LogType_CredentialRemoval,
			RemovalLog: &clientmodels.RemovalLog{
				Credentials: removedCreds,
			},
		}, nil
	}

	return clientmodels.LogInfo{}, nil
}

// disclosedAttributesToLogCredentials converts IRMA disclosed attributes to LogCredential list.
// Attributes are ordered per the credential type definition.
func disclosedAttributesToLogCredentials(irmaConfig *irma.Configuration, attributes [][]*irma.DisclosedAttribute) ([]clientmodels.LogCredential, error) {
	// Group disclosed attributes by credential type, preserving per-attr metadata
	grouped := map[irma.CredentialTypeIdentifier]map[string]*irma.DisclosedAttribute{}
	issuanceTimes := map[irma.CredentialTypeIdentifier]int64{}

	for _, con := range attributes {
		for _, attr := range con {
			credTypeId := attr.Identifier.CredentialTypeIdentifier()
			if _, ok := grouped[credTypeId]; !ok {
				grouped[credTypeId] = map[string]*irma.DisclosedAttribute{}
				issuanceTimes[credTypeId] = time.Time(attr.IssuanceTime).Unix()
			}
			grouped[credTypeId][attr.Identifier.Name()] = attr
		}
	}

	result := []clientmodels.LogCredential{}
	for credTypeId, disclosedByName := range grouped {
		credTypeInfo := irmaConfig.CredentialTypes[credTypeId]
		issuer := irmaConfig.Issuers[credTypeInfo.IssuerIdentifier()]

		// Build attributes in display order, only for those that were disclosed
		attributes := []clientmodels.Attribute{}
		for _, atType := range sortedAttributeTypes(credTypeInfo.AttributeTypes) {
			if atType.RevocationAttribute {
				continue
			}
			attr, disclosed := disclosedByName[atType.ID]
			if !disclosed {
				continue
			}
			rawVal := irma.TranslatedString(attr.Value)
			description := clientmodels.TranslatedString(atType.Description)
			name := clientmodels.TranslatedString(atType.Name)
			attributes = append(attributes, clientmodels.Attribute{
				ClaimPath:   []any{atType.ID},
				DisplayName: &name,
				Description: &description,
				Value:       buildAttributeValue(atType.DisplayHint, &rawVal),
			})
		}

		result = append(result, clientmodels.LogCredential{
			CredentialId: credTypeId.String(),
			Formats:      []clientmodels.CredentialFormat{clientmodels.Format_Idemix},
			Image:        clientmodels.ImageFromFile(credTypeInfo.Logo(irmaConfig)),
			Name:         clientmodels.TranslatedString(credTypeInfo.Name),
			Issuer:       buildIssuerTrustedParty(irmaConfig, issuer),
			Attributes:   attributes,
			IssuanceDate: issuanceTimes[credTypeId],
			IssueURL:     convertOptionalTranslatedString(credTypeInfo.IssueURL),
		})
	}
	return result, nil
}

// issuedCredentialsToLogCredentials converts an IRMA credential info list to LogCredential list.
func issuedCredentialsToLogCredentials(irmaConfig *irma.Configuration, creds irma.CredentialInfoList) ([]clientmodels.LogCredential, error) {
	result := []clientmodels.LogCredential{}
	for _, cred := range creds {
		if cred == nil {
			continue
		}

		credTypeId := cred.Identifier()
		credTypeInfo := irmaConfig.CredentialTypes[credTypeId]
		issuer := irmaConfig.Issuers[credTypeInfo.IssuerIdentifier()]

		formats := []clientmodels.CredentialFormat{clientmodels.Format_Idemix}
		if cred.InstanceCount != nil && *cred.InstanceCount > 0 {
			formats = append(formats, clientmodels.Format_SdJwtVc)
		}

		attributes := []clientmodels.Attribute{}
		for _, atType := range sortedAttributeTypes(credTypeInfo.AttributeTypes) {
			if atType.RevocationAttribute {
				continue
			}
			rawVal := irma.TranslatedString(cred.Attributes[atType.GetAttributeTypeIdentifier()])
			description := clientmodels.TranslatedString(atType.Description)
			name := clientmodels.TranslatedString(atType.Name)
			attributes = append(attributes, clientmodels.Attribute{
				ClaimPath:   []any{atType.ID},
				DisplayName: &name,
				Description: &description,
				Value:       buildAttributeValue(atType.DisplayHint, &rawVal),
			})
		}

		result = append(result, clientmodels.LogCredential{
			CredentialId:        credTypeId.String(),
			Formats:             formats,
			Image:               clientmodels.ImageFromFile(credTypeInfo.Logo(irmaConfig)),
			Name:                clientmodels.TranslatedString(credTypeInfo.Name),
			Issuer:              buildIssuerTrustedParty(irmaConfig, issuer),
			Attributes:          attributes,
			IssuanceDate:        time.Time(cred.SignedOn).Unix(),
			ExpiryDate:          time.Time(cred.Expires).Unix(),
			Revoked:             cred.Revoked,
			RevocationSupported: cred.RevocationSupported,
			IssueURL:            convertOptionalTranslatedString(credTypeInfo.IssueURL),
		})
	}
	return result, nil
}

// openid4vpCredentialLogsToLogCredentials converts legacy OpenID4VP credential logs that were
// stored in the IRMA storage (as irmaclient.CredentialLog) to the new LogCredential list,
// enriched with display metadata from irmaConfig.
func openid4vpCredentialLogsToLogCredentials(irmaConfig *irma.Configuration, logs []irmaclient.CredentialLog) []clientmodels.LogCredential {
	result := []clientmodels.LogCredential{}
	for _, log := range logs {
		credTypeId := irma.NewCredentialTypeIdentifier(log.CredentialType)
		credTypeInfo := irmaConfig.CredentialTypes[credTypeId]
		issuer := irmaConfig.Issuers[credTypeInfo.IssuerIdentifier()]

		formats := make([]clientmodels.CredentialFormat, len(log.Formats))
		for i, f := range log.Formats {
			formats[i] = clientmodels.CredentialFormat(f)
		}

		attributes := []clientmodels.Attribute{}
		for _, atType := range sortedAttributeTypes(credTypeInfo.AttributeTypes) {
			if atType.RevocationAttribute {
				continue
			}
			rawVal, disclosed := log.Attributes[atType.ID]
			if !disclosed {
				continue
			}
			v := rawVal
			irmaVal := irma.NewTranslatedString(&v)
			description := clientmodels.TranslatedString(atType.Description)
			name := clientmodels.TranslatedString(atType.Name)
			attributes = append(attributes, clientmodels.Attribute{
				ClaimPath:   []any{atType.ID},
				DisplayName: &name,
				Description: &description,
				Value:       buildAttributeValue(atType.DisplayHint, &irmaVal),
			})
		}

		result = append(result, clientmodels.LogCredential{
			CredentialId: log.CredentialType,
			Formats:      formats,
			Image:        clientmodels.ImageFromFile(credTypeInfo.Logo(irmaConfig)),
			Name:         clientmodels.TranslatedString(credTypeInfo.Name),
			Issuer:       buildIssuerTrustedParty(irmaConfig, issuer),
			Attributes:   attributes,
			IssueURL:     convertOptionalTranslatedString(credTypeInfo.IssueURL),
		})
	}
	return result
}

func (client *Client) rawLogEntriesToLogInfo(entries []*irmaclient.LogEntry) ([]clientmodels.LogInfo, error) {
	result := []clientmodels.LogInfo{}
	for _, e := range entries {
		info, err := client.rawLogEntryToLogInfo(e)
		if err != nil {
			return nil, fmt.Errorf("failed to convert log entry to info: %v", err)
		}
		result = append(result, info)
	}
	return result, nil
}
