package client

import (
	"crypto/rand"
	"crypto/sha256"
	"encoding/json"
	"errors"
	"fmt"
	"slices"
	"strconv"

	"github.com/privacybydesign/irmago/common/clientmodels"
	"github.com/privacybydesign/irmago/eudi/openid4vci"
	openid4vpclient "github.com/privacybydesign/irmago/eudi/openid4vp/client"
	"github.com/privacybydesign/irmago/irma"
	"github.com/privacybydesign/irmago/irma/irmaclient"
)

type session struct {
	State                      *clientmodels.SessionState
	handler                    clientmodels.SessionHandler
	permissionHandler          irmaclient.PermissionHandler
	pinHandler                 irmaclient.PinHandler
	client                     *Client
	dismisser                  irmaclient.SessionDismisser
	chained                    bool
	authCodeHandler            openid4vci.AuthCodeHandler
	preAuthorizedCodeHandler   openid4vci.TokenPermissionHandler
	openid4vpPermissionHandler openid4vpclient.PermissionHandler
	openid4vpHashToQueryId     map[string]string // credential hash → DCQL query ID
	// Hashes of credentials that already existed when the disclosure plan was first created.
	// Used to exclude pre-existing credentials from WrongCredentialIssued detection.
	preExistingCredentialHashes map[string]struct{}
}

func (s *session) dispatchState() {
	s.handler.UpdateSession(*s.State)
}

// snapshotPreExistingCredentials records the hashes of all credentials that exist
// before issuance-during-disclosure begins. Only called once per session; subsequent
// calls are no-ops so the snapshot reflects the state at plan creation time.
func (s *session) snapshotPreExistingCredentials(credentials []*clientmodels.Credential) {
	if s.preExistingCredentialHashes != nil {
		return
	}
	s.preExistingCredentialHashes = make(map[string]struct{}, len(credentials))
	for _, c := range credentials {
		s.preExistingCredentialHashes[c.Hash] = struct{}{}
	}
}

func (s *session) error(err error) {
	s.State.Status = clientmodels.Status_Error
	var irmaErr *irma.SessionError
	if errors.As(err, &irmaErr) {
		s.State.Error = newSessionError(irmaErr)
	} else {
		s.State.Error = newSessionError(&irma.SessionError{Err: err, ErrorType: irma.ErrorApi, Info: err.Error()})
	}
	s.dispatchState()
}

func newSessionError(err *irma.SessionError) *clientmodels.SessionError {
	var remoteError *clientmodels.RemoteError
	if err.RemoteError != nil {
		remoteError = &clientmodels.RemoteError{
			Status:      err.RemoteError.Status,
			ErrorName:   err.RemoteError.ErrorName,
			Description: err.RemoteError.Description,
			Message:     err.RemoteError.Message,
			Stacktrace:  err.RemoteError.Stacktrace,
		}
	}
	return &clientmodels.SessionError{
		ErrorType:    string(err.ErrorType),
		WrappedError: err.WrappedError(),
		Info:         err.Info,
		RemoteError:  remoteError,
		RemoteStatus: err.RemoteStatus,
		Stack:        err.Stack(),
	}
}

type sessionManager struct {
	Sessions       map[int]*session
	NextId         int
	SessionHandler clientmodels.SessionHandler
	Client         *Client
}

func (m *sessionManager) Clear() {
	m.Sessions = map[int]*session{}
	m.NextId = 0
}

func (m *sessionManager) DeleteSession(id int) {
	delete(m.Sessions, id)
}

func (m *sessionManager) NewSession() *session {
	// TODO: use locking here to update the session ID
	m.NextId += 1
	s := &session{
		State: &clientmodels.SessionState{
			Id: m.NextId,
		},
		handler: m.SessionHandler,
		client:  m.Client,
	}
	m.Sessions[m.NextId] = s
	return s
}

func requestorInfoToTrustedParty(info *irma.RequestorInfo) clientmodels.TrustedParty {
	return clientmodels.TrustedParty{
		Id:        info.ID.String(),
		Name:      clientmodels.TranslatedString(info.Name),
		ImagePath: info.LogoPath,
		Parent:    nil,
		Verified:  !info.Unverified,
	}
}

func requestorInfoToTrustedPartyPtr(info *irma.RequestorInfo) *clientmodels.TrustedParty {
	if info == nil {
		return nil
	}
	tp := requestorInfoToTrustedParty(info)
	return &tp
}

// filterRandomBlindAttributes removes random blind attributes from offered credentials.
// These attributes are generated by the issuance protocol and have no user-meaningful value
// at issuance permission time.
func filterRandomBlindAttributes(irmaConfig *irma.Configuration, credentials []*clientmodels.Credential) {
	for _, cred := range credentials {
		credTypeID := irma.NewCredentialTypeIdentifier(cred.CredentialId)
		credType, ok := irmaConfig.CredentialTypes[credTypeID]
		if !ok {
			continue
		}
		randomBlindIDs := make(map[string]struct{})
		for _, at := range credType.AttributeTypes {
			if at.RandomBlind {
				randomBlindIDs[at.ID] = struct{}{}
			}
		}
		if len(randomBlindIDs) == 0 {
			continue
		}
		filtered := make([]clientmodels.Attribute, 0, len(cred.Attributes))
		for _, attr := range cred.Attributes {
			if _, isBlind := randomBlindIDs[attr.Id]; !isBlind {
				filtered = append(filtered, attr)
			}
		}
		cred.Attributes = filtered
	}
}

func findCredential(credentials []*clientmodels.Credential, hash string) *clientmodels.SelectableCredentialInstance {
	for _, c := range credentials {
		// each format has its own hash for the corresponding instance
		for format, h := range c.CredentialInstanceIds {
			if h == hash {
				return &clientmodels.SelectableCredentialInstance{
					CredentialId:                c.CredentialId,
					Hash:                        h,
					ImagePath:                   c.ImagePath,
					Name:                        c.Name,
					Issuer:                      c.Issuer,
					Format:                      format,
					BatchInstanceCountRemaining: c.BatchInstanceCountsRemaining[format],
					Attributes:                  c.Attributes,
					IssuanceDate:                c.IssuanceDate,
					ExpiryDate:                  c.ExpiryDate,
					Revoked:                     c.Revoked,
					RevocationSupported:         c.RevocationSupported,
					IssueURL:                    c.IssueURL,
				}
			}
		}
	}
	return nil
}

func createIssuanceSteps(
	irmaConfig *irma.Configuration,
	credentials []*clientmodels.Credential,
	candidates [][]irmaclient.DisclosureCandidates,
) ([]clientmodels.IssuanceStep, error) {
	// for each disjunction that is not satisfiable we need to give the user the option to select
	// from any of the options (inner cons) beloning to that disjunction
	unsatisfiedDisjunctionIndices := []int{}
	result := []clientmodels.IssuanceStep{}

	for i, discon := range candidates {
		disconSatisfied := false
		for _, con := range discon {
			conSatisfied := true
			for _, attr := range con {
				if findCredential(credentials, attr.CredentialHash) == nil {
					conSatisfied = false
				}
			}
			if conSatisfied {
				disconSatisfied = true
			}
		}
		if !disconSatisfied {
			unsatisfiedDisjunctionIndices = append(unsatisfiedDisjunctionIndices, i)
		}
	}

	for _, i := range unsatisfiedDisjunctionIndices {
		discon := candidates[i]
		options := []*clientmodels.CredentialDescriptor{}
		for _, con := range discon {
			descriptor, err := createCredentialDescriptor(irmaConfig, con)
			if err != nil {
				return nil, err
			}
			options = append(options, descriptor)
		}
		result = append(result, clientmodels.IssuanceStep{
			Options: options,
		})
	}

	return result, nil
}

func createDisclosureChoicesOverview(
	irmaConfig *irma.Configuration,
	credentials []*clientmodels.Credential,
	candidates [][]irmaclient.DisclosureCandidates,
) ([]clientmodels.DisclosurePickOne, error) {
	result := []clientmodels.DisclosurePickOne{}
	// for each discon we create a disclosure pick one
	for _, discon := range candidates {
		choice := clientmodels.DisclosurePickOne{}

		choiceTemplates := map[string]*clientmodels.CredentialDescriptor{}        // key: credentialId
		filteredByHash := map[string]*clientmodels.SelectableCredentialInstance{} // key: credentialHash
		ownedOrder := []string{}                                                  // preserves insertion order of hashes

		for _, con := range discon {
			// if at least one of the cons inside of a discon is empty
			// then the discon is satisfiable by picking no credentials at all
			// therefore the choice is optional
			if len(con) == 0 {
				choice.Optional = true
			}
			for _, attr := range con {
				hash := attr.AttributeIdentifier.CredentialHash

				if hash == "" {
					t := attr.CredentialIdentifier().Type
					id := t.String()

					// Ensure template exists once per type in this choice
					if _, ok := choiceTemplates[id]; !ok {
						descriptor, err := getCredentialDescriptor(irmaConfig, t)
						if err != nil {
							return nil, err
						}
						choiceTemplates[id] = descriptor
						choice.ObtainableOptions = append(choice.ObtainableOptions, descriptor)
					}

					// Populate RequestedValue for the requested attribute
					attrName := attr.AttributeIdentifier.Type.Name()
					for i := range choiceTemplates[id].Attributes {
						if choiceTemplates[id].Attributes[i].Id == attrName {
							requestedValue := &clientmodels.AttributeValue{
								Type: clientmodels.AttributeType_TranslatedString,
							}
							if attr.Value != nil {
								requestedValue.TranslatedString = convertOptionalTranslatedString(&attr.Value)
							}
							choiceTemplates[id].Attributes[i].RequestedValue = requestedValue
							break
						}
					}
				} else {
					// Present attribute => owned credential instance (but we filter attributes)
					orig := findCredential(credentials, hash)
					if orig == nil {
						return nil, fmt.Errorf("failed to find credential for hash: %v", hash)
					}

					// Get or create filtered instance for this credential hash
					f, ok := filteredByHash[hash]
					if !ok {
						cp := *orig
						f = &cp
						f.Attributes = []clientmodels.Attribute{}
						filteredByHash[hash] = f
						ownedOrder = append(ownedOrder, hash)
					}

					// TODO: make this more independent and compatible with more complex claim paths
					attrID := attr.AttributeIdentifier
					val, ok := lookupAttrValue(orig, attrID)
					if !ok {
						return nil, fmt.Errorf("credential %s does not contain attribute %v", hash, attrID)
					}

					f.Attributes = append(f.Attributes, val)
				}
			}
		}
		// Collect OwnedOptions in the order candidates were encountered.
		for _, hash := range ownedOrder {
			choice.OwnedOptions = append(choice.OwnedOptions, filteredByHash[hash])
		}
		result = append(result, choice)
	}

	return result, nil
}

// returns the list of issued credential ids compared to the steps,
// the most recently issued credential with the right type but wrong attribute values
// (only for unsatisfied steps), and whether the steps are satisfied.
// preExistingHashes contains hashes of credentials that existed before the disclosure session,
// which are excluded from wrong credential detection.
// previousWrongHash is the hash of the wrong credential from the previous plan update,
// used to prefer a newer wrong credential when issuance dates are equal.
func getIssuedSinceOriginalPlan(
	steps []clientmodels.IssuanceStep,
	allCredentials []*clientmodels.Credential,
	preExistingHashes map[string]struct{},
	previousWrongHash string,
) (issued map[string]struct{}, lastWrongCredential *clientmodels.Credential, satisfied bool) {
	issued = map[string]struct{}{}
	numSatisfiedSteps := 0

	for _, step := range steps {
		stepSatisfied := false
		for _, option := range step.Options {
			hasSatisfyingMatch := false
			for _, c := range allCredentials {
				if c.CredentialId != option.CredentialId {
					continue
				}
				// now check if it satisfies the values specified in the previous issuance step
				attsStatisfied, _ := SatisfiesRequestedAttributes(c.Attributes, option.Attributes)
				if attsStatisfied {
					hasSatisfyingMatch = true
					break
				}
				// Skip credentials that existed before the disclosure session started;
				// only credentials issued during this session should be reported as wrong.
				if _, preExisting := preExistingHashes[c.Hash]; preExisting {
					continue
				}
				// A credential with the right type exists but has wrong attribute values.
				// Keep the most recently issued one so the frontend can show it.
				// When issuance dates are equal, prefer a credential that differs from the
				// previously reported wrong credential, as it is more likely to be newly issued.
				if lastWrongCredential == nil || c.IssuanceDate > lastWrongCredential.IssuanceDate {
					lastWrongCredential = filterCredentialToMismatchedAttributes(c, option.Attributes)
				} else if c.IssuanceDate == lastWrongCredential.IssuanceDate &&
					lastWrongCredential.Hash == previousWrongHash && c.Hash != previousWrongHash {
					lastWrongCredential = filterCredentialToMismatchedAttributes(c, option.Attributes)
				}
			}
			if hasSatisfyingMatch {
				issued[option.CredentialId] = struct{}{}
				stepSatisfied = true
			}
		}
		if stepSatisfied {
			numSatisfiedSteps += 1
			// Clear the wrong credential if this step is now satisfied
			lastWrongCredential = nil
		}
	}

	satisfied = numSatisfiedSteps == len(steps)
	return
}

// filterCredentialToMismatchedAttributes returns a copy of the credential containing only
// the attributes that have a pre-defined requested value that doesn't match the credential's
// actual value. Each included attribute gets the RequestedValue from the option so the
// frontend can show both the actual and expected values side by side.
func filterCredentialToMismatchedAttributes(cred *clientmodels.Credential, requestedAttrs []clientmodels.Attribute) *clientmodels.Credential {
	requestedByID := make(map[string]*clientmodels.Attribute, len(requestedAttrs))
	for i := range requestedAttrs {
		requestedByID[requestedAttrs[i].Id] = &requestedAttrs[i]
	}

	var filtered []clientmodels.Attribute
	for _, attr := range cred.Attributes {
		req, ok := requestedByID[attr.Id]
		if !ok || req.RequestedValue == nil || !req.RequestedValue.HasValue() {
			continue
		}
		// Check if the actual value doesn't match the requested value
		satisfied, _ := SatisfiesRequestedAttributes(
			[]clientmodels.Attribute{attr},
			[]clientmodels.Attribute{*req},
		)
		if !satisfied {
			filtered = append(filtered, clientmodels.Attribute{
				Id:             attr.Id,
				DisplayName:    attr.DisplayName,
				Description:    attr.Description,
				Value:          attr.Value,
				RequestedValue: req.RequestedValue,
			})
		}
	}

	result := *cred
	result.Attributes = filtered
	return &result
}

func createDisclosurePlan(
	oldDisclosurePlan *clientmodels.DisclosurePlan,
	irmaConfig *irma.Configuration,
	credentials []*clientmodels.Credential,
	candidates [][]irmaclient.DisclosureCandidates,
	preExistingCredentialHashes map[string]struct{},
) (*clientmodels.DisclosurePlan, error) {
	newPlan := &clientmodels.DisclosurePlan{}
	// there's no plan yet, so make a new one
	if oldDisclosurePlan == nil {
		issuanceSteps, err := createIssuanceSteps(irmaConfig, credentials, candidates)
		if err != nil {
			return nil, fmt.Errorf("failed to create issuance steps: %w", err)
		}

		// the current disclosure flow is not satisfyable without issuance
		if len(issuanceSteps) != 0 {
			return &clientmodels.DisclosurePlan{
				IssueDuringDislosure: &clientmodels.IssueDuringDislosure{
					IssuedCredentialIds: map[string]struct{}{},
					Steps:               issuanceSteps,
				},
			}, nil
		}
	} else {
		// update the existing issuance plan if it exists
		lastIssuancePlan := oldDisclosurePlan.IssueDuringDislosure
		if lastIssuancePlan != nil {
			var previousWrongHash string
			if lastIssuancePlan.WrongCredentialIssued != nil {
				previousWrongHash = lastIssuancePlan.WrongCredentialIssued.Hash
			}
			issued, lastWrongCredential, satisfied := getIssuedSinceOriginalPlan(
				lastIssuancePlan.Steps, credentials, preExistingCredentialHashes, previousWrongHash,
			)
			newPlan.IssueDuringDislosure = &clientmodels.IssueDuringDislosure{
				Steps:                 lastIssuancePlan.Steps,
				IssuedCredentialIds:   issued,
				WrongCredentialIssued: lastWrongCredential,
			}

			// still not satisfied, so no disclosure overview should be made
			// return the old issuance steps with the credentials issued since starting the session
			if !satisfied {
				return newPlan, nil
			}
		}
	}

	// if the request is satisfiable we can continue to the next stage: picking disclosure choices
	disclosureChoices, err := createDisclosureChoicesOverview(irmaConfig, credentials, candidates)
	if err != nil {
		return nil, fmt.Errorf("failed to create disclosure choices overview: %w", err)
	}
	newPlan.DisclosureChoicesOverview = disclosureChoices
	return newPlan, nil
}

func lookupAttrValue(orig *clientmodels.SelectableCredentialInstance, id *irma.AttributeIdentifier) (clientmodels.Attribute, bool) {
	index := slices.IndexFunc(orig.Attributes, func(att clientmodels.Attribute) bool {
		return att.Id == id.Type.Name()
	})
	if index >= 0 {
		return orig.Attributes[index], true
	}
	return clientmodels.Attribute{}, false
}

func (s *session) setPseudoRandomOpenIdState() {
	if len(s.State.StateSalt) == 0 {
		salt := [16]byte{}
		_, err := rand.Read(salt[:])
		if err != nil {
			panic(fmt.Sprintf("failed to generate random state salt: %v", err))
		}

		s.State.StateSalt = salt[:]
	}

	stateBytes := append(s.State.StateSalt, []byte(strconv.Itoa(s.State.Id))...)

	s.State.Oid4VciState = fmt.Sprintf("%x", sha256.Sum256(stateBytes))
}

// =====================================================================================

func choicesToAnswer(choices []clientmodels.DisclosureDisconSelection) (*irma.DisclosureChoice, error) {
	result := &irma.DisclosureChoice{
		Attributes: [][]*irma.AttributeIdentifier{},
	}

	for _, choice := range choices {
		attrs := []*irma.AttributeIdentifier{}
		for _, cred := range choice.Credentials {
			for _, attr := range cred.AttributePaths {
				attrs = append(attrs, &irma.AttributeIdentifier{
					// this for now assumes only a single claim path item
					Type: irma.NewAttributeTypeIdentifier(
						fmt.Sprintf("%s.%s", cred.CredentialId, attr[0].(string)),
					),
					CredentialHash: cred.CredentialHash,
				})
			}
		}
		result.Attributes = append(result.Attributes, attrs)
	}

	return result, nil
}

// =====================================================================================

func (client *Client) HandleUserInteraction(userInteraction clientmodels.SessionUserInteraction) error {
	session, ok := client.sessionManager.Sessions[userInteraction.SessionId]
	if !ok {
		return fmt.Errorf("no session with id %v", userInteraction.SessionId)
	}
	switch userInteraction.Type {
	case clientmodels.UI_Permission:
		payload := userInteraction.Payload.(clientmodels.SessionPermissionInteractionPayload)
		if session.openid4vpPermissionHandler != nil {
			// OpenID4VP flow: convert UI selections to DisclosureSelections
			selections := disclosureChoicesToOpenID4VPSelections(payload.DisclosureChoices, session.openid4vpHashToQueryId)
			session.openid4vpPermissionHandler(payload.Granted, selections)
		} else {
			// IRMA flow
			choices, err := choicesToAnswer(payload.DisclosureChoices)
			if err != nil {
				return err
			}
			session.permissionHandler(payload.Granted, choices)
		}
	case clientmodels.UI_EnteredPin:
		payload := userInteraction.Payload.(clientmodels.PinInteractionPayload)
		session.pinHandler(payload.Proceed, payload.Pin)
	case clientmodels.UI_DismissSession:
		session.dismisser.Dismiss()
		// Ensure the session is always marked as dismissed, regardless of protocol.
		// Some protocol implementations (e.g. OpenID4VP) don't call Cancelled() from Dismiss().
		if session.State.Status != clientmodels.Status_Dismissed {
			session.State.Status = clientmodels.Status_Dismissed
			session.dispatchState()
		}
	case clientmodels.UI_PreAuthorizedCode:
		payload := userInteraction.Payload.(clientmodels.SessionPreAuthorizedCodeInteractionPayload)
		session.preAuthorizedCodeHandler(payload.Proceed, payload.TransactionCode)
	case clientmodels.UI_AuthorizationCode:
		payload := userInteraction.Payload.(clientmodels.SessionAuthCodeInteractionPayload)
		session.authCodeHandler(payload.Proceed, payload.Code)
	}

	return nil
}

func (client *Client) NewSession(sessionrequest string) {
	session := client.sessionManager.NewSession()
	state := session.State

	var sessionReq SessionRequestData
	err := json.Unmarshal([]byte(sessionrequest), &sessionReq)
	if err != nil {
		irma.Logger.Errorf("failed to parse session request: %v\n", err)
		session.error(err)
		client.sessionManager.DeleteSession(session.State.Id)
		return
	}

	state.Protocol = sessionReq.Protocol
	state.ContinueOnSecondDevice = sessionReq.ContinueOnSecondDevice

	switch sessionReq.Type {
	case irma.ActionDisclosing:
		state.Type = clientmodels.Type_Disclosure
	case irma.ActionIssuing:
		state.Type = clientmodels.Type_Issuance
	case irma.ActionSigning:
		state.Type = clientmodels.Type_Signature
	}

	switch sessionReq.Protocol {
	case clientmodels.Protocol_OpenID4VP:
		session.dismisser = client.openid4vpClient.NewSession(sessionReq.URL, &openid4vpSessionAdapter{session: session})
	case clientmodels.Protocol_OpenID4VCI:
		session.dismisser = client.openid4vciClient.NewSession(sessionReq.URL, &openid4vciSessionAdapter{session: session})
	default:
		session.dismisser = client.irmaClient.NewSession(sessionrequest, &irmaSessionAdapter{session: session})
	}
}
