// Code generated by protoc-gen-go. DO NOT EDIT.
// source: IRMASchemeMetadata.proto

package irmaproto

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This mimicks IRMA scheme description.xml
type IRMASchemeMetadata struct {
	Version           int32                                      `protobuf:"varint,1,opt,name=version" json:"version,omitempty"`
	Id                string                                     `protobuf:"bytes,2,opt,name=id" json:"id,omitempty"`
	Url               string                                     `protobuf:"bytes,3,opt,name=url" json:"url,omitempty"`
	Name              []*IRMASchemeMetadata_LocalizedName        `protobuf:"bytes,4,rep,name=name" json:"name,omitempty"`
	Description       []*IRMASchemeMetadata_LocalizedDescription `protobuf:"bytes,5,rep,name=description" json:"description,omitempty"`
	Keyshareserver    string                                     `protobuf:"bytes,6,opt,name=keyshareserver" json:"keyshareserver,omitempty"`
	Keysharewebsite   string                                     `protobuf:"bytes,7,opt,name=keysharewebsite" json:"keysharewebsite,omitempty"`
	Keyshareattribute string                                     `protobuf:"bytes,8,opt,name=keyshareattribute" json:"keyshareattribute,omitempty"`
	Contact           string                                     `protobuf:"bytes,9,opt,name=contact" json:"contact,omitempty"`
}

func (m *IRMASchemeMetadata) Reset()                    { *m = IRMASchemeMetadata{} }
func (m *IRMASchemeMetadata) String() string            { return proto.CompactTextString(m) }
func (*IRMASchemeMetadata) ProtoMessage()               {}
func (*IRMASchemeMetadata) Descriptor() ([]byte, []int) { return fileDescriptor3, []int{0} }

func (m *IRMASchemeMetadata) GetVersion() int32 {
	if m != nil {
		return m.Version
	}
	return 0
}

func (m *IRMASchemeMetadata) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *IRMASchemeMetadata) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

func (m *IRMASchemeMetadata) GetName() []*IRMASchemeMetadata_LocalizedName {
	if m != nil {
		return m.Name
	}
	return nil
}

func (m *IRMASchemeMetadata) GetDescription() []*IRMASchemeMetadata_LocalizedDescription {
	if m != nil {
		return m.Description
	}
	return nil
}

func (m *IRMASchemeMetadata) GetKeyshareserver() string {
	if m != nil {
		return m.Keyshareserver
	}
	return ""
}

func (m *IRMASchemeMetadata) GetKeysharewebsite() string {
	if m != nil {
		return m.Keysharewebsite
	}
	return ""
}

func (m *IRMASchemeMetadata) GetKeyshareattribute() string {
	if m != nil {
		return m.Keyshareattribute
	}
	return ""
}

func (m *IRMASchemeMetadata) GetContact() string {
	if m != nil {
		return m.Contact
	}
	return ""
}

type IRMASchemeMetadata_LocalizedName struct {
	Lang string `protobuf:"bytes,1,opt,name=lang" json:"lang,omitempty"`
	Name string `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
}

func (m *IRMASchemeMetadata_LocalizedName) Reset()         { *m = IRMASchemeMetadata_LocalizedName{} }
func (m *IRMASchemeMetadata_LocalizedName) String() string { return proto.CompactTextString(m) }
func (*IRMASchemeMetadata_LocalizedName) ProtoMessage()    {}
func (*IRMASchemeMetadata_LocalizedName) Descriptor() ([]byte, []int) {
	return fileDescriptor3, []int{0, 0}
}

func (m *IRMASchemeMetadata_LocalizedName) GetLang() string {
	if m != nil {
		return m.Lang
	}
	return ""
}

func (m *IRMASchemeMetadata_LocalizedName) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type IRMASchemeMetadata_LocalizedDescription struct {
	Lang string `protobuf:"bytes,1,opt,name=lang" json:"lang,omitempty"`
	Name string `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
}

func (m *IRMASchemeMetadata_LocalizedDescription) Reset() {
	*m = IRMASchemeMetadata_LocalizedDescription{}
}
func (m *IRMASchemeMetadata_LocalizedDescription) String() string { return proto.CompactTextString(m) }
func (*IRMASchemeMetadata_LocalizedDescription) ProtoMessage()    {}
func (*IRMASchemeMetadata_LocalizedDescription) Descriptor() ([]byte, []int) {
	return fileDescriptor3, []int{0, 1}
}

func (m *IRMASchemeMetadata_LocalizedDescription) GetLang() string {
	if m != nil {
		return m.Lang
	}
	return ""
}

func (m *IRMASchemeMetadata_LocalizedDescription) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func init() {
	proto.RegisterType((*IRMASchemeMetadata)(nil), "irmaproto.IRMASchemeMetadata")
	proto.RegisterType((*IRMASchemeMetadata_LocalizedName)(nil), "irmaproto.IRMASchemeMetadata.LocalizedName")
	proto.RegisterType((*IRMASchemeMetadata_LocalizedDescription)(nil), "irmaproto.IRMASchemeMetadata.LocalizedDescription")
}

func init() { proto.RegisterFile("IRMASchemeMetadata.proto", fileDescriptor3) }

var fileDescriptor3 = []byte{
	// 289 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x90, 0xbb, 0x4e, 0xf3, 0x40,
	0x10, 0x85, 0xe5, 0x4b, 0x92, 0xdf, 0x13, 0xfd, 0x01, 0x46, 0x14, 0xab, 0x54, 0x16, 0x05, 0xb2,
	0x04, 0x72, 0x11, 0x0a, 0x3a, 0x10, 0x12, 0x0d, 0x12, 0xa1, 0x58, 0x78, 0x81, 0xb1, 0x3d, 0x22,
	0x2b, 0x7c, 0x89, 0xd6, 0x9b, 0x20, 0x78, 0x74, 0x2a, 0xe4, 0x41, 0xe6, 0x92, 0xa4, 0x48, 0x77,
	0xe6, 0xf8, 0xcc, 0xf8, 0xec, 0x07, 0xea, 0x4e, 0xcf, 0x6f, 0x1e, 0xf3, 0x05, 0x57, 0x3c, 0x67,
	0x47, 0x05, 0x39, 0x4a, 0x97, 0xb6, 0x71, 0x0d, 0x46, 0xc6, 0x56, 0x24, 0xf2, 0xe4, 0x23, 0x00,
	0xdc, 0xce, 0xa1, 0x82, 0xd1, 0x9a, 0x6d, 0x6b, 0x9a, 0x5a, 0x79, 0xb1, 0x97, 0x0c, 0x74, 0x3f,
	0xe2, 0x04, 0x7c, 0x53, 0x28, 0x3f, 0xf6, 0x92, 0x48, 0xfb, 0xa6, 0xc0, 0x43, 0x08, 0x56, 0xb6,
	0x54, 0x81, 0x18, 0x9d, 0xc4, 0x6b, 0x08, 0x6b, 0xaa, 0x58, 0x85, 0x71, 0x90, 0x8c, 0x67, 0x67,
	0xe9, 0xf7, 0xcf, 0xd2, 0x1d, 0x85, 0xee, 0x9b, 0x9c, 0x4a, 0xf3, 0xce, 0xc5, 0x03, 0x55, 0xac,
	0x65, 0x11, 0x9f, 0x60, 0x5c, 0x70, 0x9b, 0x5b, 0xb3, 0x74, 0x5d, 0x81, 0x81, 0xdc, 0x99, 0xed,
	0x79, 0xe7, 0xf6, 0x67, 0x53, 0xff, 0x3e, 0x83, 0xa7, 0x30, 0x79, 0xe1, 0xb7, 0x76, 0x41, 0x96,
	0x5b, 0xb6, 0x6b, 0xb6, 0x6a, 0x28, 0x9d, 0x37, 0x5c, 0x4c, 0xe0, 0xa0, 0x77, 0x5e, 0x39, 0x6b,
	0x8d, 0x63, 0x35, 0x92, 0xe0, 0xa6, 0x8d, 0xe7, 0x70, 0xd4, 0x5b, 0xe4, 0x9c, 0x35, 0xd9, 0xca,
	0xb1, 0xfa, 0x27, 0xd9, 0xed, 0x0f, 0x1d, 0xd2, 0xbc, 0xa9, 0x1d, 0xe5, 0x4e, 0x45, 0x92, 0xe9,
	0xc7, 0xe9, 0x25, 0xfc, 0xff, 0x83, 0x01, 0x11, 0xc2, 0x92, 0xea, 0x67, 0x41, 0x1f, 0x69, 0xd1,
	0x9d, 0x27, 0x54, 0xbf, 0xc8, 0x8b, 0x9e, 0x5e, 0xc1, 0xf1, 0xae, 0x77, 0xef, 0xbb, 0x9f, 0x0d,
	0x05, 0xe7, 0xc5, 0x67, 0x00, 0x00, 0x00, 0xff, 0xff, 0xb9, 0x36, 0xea, 0xfa, 0x2a, 0x02, 0x00,
	0x00,
}
