// Code generated by protoc-gen-go. DO NOT EDIT.
// source: IRMAIssuerMetadata.proto

package irmaproto

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This mimicks IRMA issuer description.xml
type IRMAIssuerMetadata struct {
	Version        int32                               `protobuf:"varint,1,opt,name=version" json:"version,omitempty"`
	Id             string                              `protobuf:"bytes,2,opt,name=id" json:"id,omitempty"`
	Shortname      []*IRMAIssuerMetadata_LocalizedName `protobuf:"bytes,4,rep,name=shortname" json:"shortname,omitempty"`
	Name           []*IRMAIssuerMetadata_LocalizedName `protobuf:"bytes,5,rep,name=name" json:"name,omitempty"`
	Schememanager  string                              `protobuf:"bytes,6,opt,name=schememanager" json:"schememanager,omitempty"`
	Contactaddress string                              `protobuf:"bytes,7,opt,name=contactaddress" json:"contactaddress,omitempty"`
	Contactemail   string                              `protobuf:"bytes,8,opt,name=contactemail" json:"contactemail,omitempty"`
	Baseurl        string                              `protobuf:"bytes,9,opt,name=baseurl" json:"baseurl,omitempty"`
}

func (m *IRMAIssuerMetadata) Reset()                    { *m = IRMAIssuerMetadata{} }
func (m *IRMAIssuerMetadata) String() string            { return proto.CompactTextString(m) }
func (*IRMAIssuerMetadata) ProtoMessage()               {}
func (*IRMAIssuerMetadata) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{0} }

func (m *IRMAIssuerMetadata) GetVersion() int32 {
	if m != nil {
		return m.Version
	}
	return 0
}

func (m *IRMAIssuerMetadata) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *IRMAIssuerMetadata) GetShortname() []*IRMAIssuerMetadata_LocalizedName {
	if m != nil {
		return m.Shortname
	}
	return nil
}

func (m *IRMAIssuerMetadata) GetName() []*IRMAIssuerMetadata_LocalizedName {
	if m != nil {
		return m.Name
	}
	return nil
}

func (m *IRMAIssuerMetadata) GetSchememanager() string {
	if m != nil {
		return m.Schememanager
	}
	return ""
}

func (m *IRMAIssuerMetadata) GetContactaddress() string {
	if m != nil {
		return m.Contactaddress
	}
	return ""
}

func (m *IRMAIssuerMetadata) GetContactemail() string {
	if m != nil {
		return m.Contactemail
	}
	return ""
}

func (m *IRMAIssuerMetadata) GetBaseurl() string {
	if m != nil {
		return m.Baseurl
	}
	return ""
}

type IRMAIssuerMetadata_LocalizedName struct {
	Lang string `protobuf:"bytes,1,opt,name=lang" json:"lang,omitempty"`
	Name string `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
}

func (m *IRMAIssuerMetadata_LocalizedName) Reset()         { *m = IRMAIssuerMetadata_LocalizedName{} }
func (m *IRMAIssuerMetadata_LocalizedName) String() string { return proto.CompactTextString(m) }
func (*IRMAIssuerMetadata_LocalizedName) ProtoMessage()    {}
func (*IRMAIssuerMetadata_LocalizedName) Descriptor() ([]byte, []int) {
	return fileDescriptor1, []int{0, 0}
}

func (m *IRMAIssuerMetadata_LocalizedName) GetLang() string {
	if m != nil {
		return m.Lang
	}
	return ""
}

func (m *IRMAIssuerMetadata_LocalizedName) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func init() {
	proto.RegisterType((*IRMAIssuerMetadata)(nil), "irmaproto.IRMAIssuerMetadata")
	proto.RegisterType((*IRMAIssuerMetadata_LocalizedName)(nil), "irmaproto.IRMAIssuerMetadata.LocalizedName")
}

func init() { proto.RegisterFile("IRMAIssuerMetadata.proto", fileDescriptor1) }

var fileDescriptor1 = []byte{
	// 256 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x50, 0xc1, 0x4a, 0xc3, 0x40,
	0x10, 0x25, 0x69, 0xda, 0x9a, 0xd1, 0xf6, 0x30, 0xa7, 0xc5, 0x53, 0x28, 0x22, 0x01, 0x21, 0x07,
	0x3d, 0x78, 0x14, 0x8f, 0x01, 0xeb, 0x21, 0x7f, 0x30, 0xcd, 0x0e, 0xed, 0x42, 0x76, 0x57, 0x76,
	0xb7, 0x1e, 0xfc, 0x09, 0x7f, 0x59, 0x3a, 0x5a, 0x25, 0xea, 0xa5, 0xb7, 0x37, 0x6f, 0xde, 0x3c,
	0xde, 0x3c, 0x50, 0x6d, 0xb7, 0x7e, 0x6c, 0x63, 0xdc, 0x73, 0x58, 0x73, 0x22, 0x4d, 0x89, 0x9a,
	0x97, 0xe0, 0x93, 0xc7, 0xd2, 0x04, 0x4b, 0x02, 0x57, 0xef, 0x13, 0xc0, 0xbf, 0x3a, 0x54, 0x30,
	0x7f, 0xe5, 0x10, 0x8d, 0x77, 0x2a, 0xab, 0xb2, 0x7a, 0xda, 0x1d, 0x47, 0x5c, 0x42, 0x6e, 0xb4,
	0xca, 0xab, 0xac, 0x2e, 0xbb, 0xdc, 0x68, 0x6c, 0xa1, 0x8c, 0x3b, 0x1f, 0x92, 0x23, 0xcb, 0xaa,
	0xa8, 0x26, 0xf5, 0xf9, 0xed, 0x4d, 0xf3, 0xed, 0xdf, 0xfc, 0x93, 0xe1, 0xc9, 0xf7, 0x34, 0x98,
	0x37, 0xd6, 0xcf, 0x64, 0xb9, 0xfb, 0xb9, 0xc6, 0x07, 0x28, 0xc4, 0x65, 0x7a, 0xba, 0x8b, 0x1c,
	0xe2, 0x15, 0x2c, 0x62, 0xbf, 0x63, 0xcb, 0x96, 0x1c, 0x6d, 0x39, 0xa8, 0x99, 0xc4, 0x1c, 0x93,
	0x78, 0x0d, 0xcb, 0xde, 0xbb, 0x44, 0x7d, 0x22, 0xad, 0x03, 0xc7, 0xa8, 0xe6, 0x22, 0xfb, 0xc5,
	0xe2, 0x0a, 0x2e, 0xbe, 0x18, 0xb6, 0x64, 0x06, 0x75, 0x26, 0xaa, 0x11, 0x77, 0xe8, 0x69, 0x43,
	0x91, 0xf7, 0x61, 0x50, 0xa5, 0xac, 0x8f, 0xe3, 0xe5, 0x3d, 0x2c, 0x46, 0x11, 0x11, 0xa1, 0x18,
	0xc8, 0x6d, 0xa5, 0xcf, 0xb2, 0x13, 0x7c, 0xe0, 0xe4, 0xe3, 0xcf, 0x3a, 0x05, 0x6f, 0x66, 0xf2,
	0xf2, 0xdd, 0x47, 0x00, 0x00, 0x00, 0xff, 0xff, 0xdd, 0x36, 0x79, 0xc2, 0xbf, 0x01, 0x00, 0x00,
}
