package mdoc

import (
	"os"
	"testing"

	"github.com/fxamacker/cbor/v2"

	"github.com/stretchr/testify/require"
)

// ============================================================
// CROSS-IMPLEMENTATION VECTOR — bytes Multipaz actually produced
// ============================================================
//
// zkp.go's CBOR shapes were written AGAINST org.multipaz.mdoc.zkp, because the
// ISO/IEC DIS 18013-5 second edition that defines them is not published -- it is
// still a draft in ballot -- and Multipaz is the stated conformance target. Until this test, that agreement was asserted
// and never checked: every other test in this package encodes with our own code
// and decodes with our own code, which passes just as happily if both sides are
// wrong in the same way.
//
// testdata/multipaz_zk_deviceresponse.cbor is a real DeviceResponse carrying a
// real longfellow-libzk-v1 proof, generated by Multipaz's own
// LongfellowZkSystem against its bundled native library and captured from
// multipaz-longfellow's SystemTest. Decoding it here is the first evidence that
// the two implementations agree about the wire.
//
// # What this vector is not
//
// It is org.iso.18013.5.1.mDL over a PROXIMITY SessionTranscript, not
// eu.europa.ec.av.1 over a DC API handover. So it exercises the ZkDocument and
// DeviceResponse encoding and says nothing about the AV profile path. A vector
// of the latter shape needs a reader that sends one.
//
// The proof is not verified here and cannot be: verification needs the native
// prover this build does not have (see ZkSystem). What is under test is the
// envelope.

const multipazVector = "testdata/multipaz_zk_deviceresponse.cbor"

func multipazDeviceResponse(t *testing.T) DeviceResponse {
	t.Helper()

	raw, err := os.ReadFile(multipazVector)
	require.NoError(t, err, "the cross-implementation vector must be present")

	var response DeviceResponse
	require.NoError(t, Unmarshal(raw, &response),
		"a DeviceResponse Multipaz produced must decode with this package's rules")
	return response
}

// TestMultipazZkDeviceResponseDecodes is the headline: their bytes, our decoder.
func TestMultipazZkDeviceResponseDecodes(t *testing.T) {
	response := multipazDeviceResponse(t)

	require.Equal(t, DeviceResponseVersionZk, response.Version,
		"a response carrying zkDocuments is a second-edition response and says so")
	require.Equal(t, ResponseStatusOK, response.Status)

	// The choice between documents and zkDocuments is per document, and this
	// response made it one way: a proof travels instead of a disclosure, so the
	// plain documents array must be absent rather than empty-but-present.
	require.Empty(t, response.Documents,
		"a ZK presentation replaces the disclosure, it does not accompany one")
	require.Len(t, response.ZkDocuments, 1)
}

// TestMultipazZkDocumentShape checks the members we encode against the ones they
// emit. A field we spelled differently would round-trip fine in our own tests and
// be silently dropped here.
func TestMultipazZkDocumentShape(t *testing.T) {
	document := multipazDeviceResponse(t).ZkDocuments[0]

	require.NotEmpty(t, document.Proof, "the proof is the point of the document")
	require.Greater(t, len(document.Proof), 100_000,
		"a longfellow proof is hundreds of kilobytes; a short one means we decoded the wrong member")

	data := document.DocumentData

	require.Equal(t, MDLDocType, data.DocType,
		"Multipaz's SystemTest proves over an mDL, not an age-verification attestation")
	require.NotEmpty(t, data.MsoX5Chain, "the proof is checked against the issuer key in this chain")
	require.False(t, data.Timestamp.IsZero(), "A.8 has the proof establish validity at a time")
}

// TestMultipazZkDeviceResponseRoundTrips closes the loop on content rather than
// on bytes.
//
// Byte-for-byte equality is deliberately NOT asserted, and the first draft of
// this test asserting it was wrong. Multipaz orders the top-level map
// version/status/zkDocuments and this package orders it
// version/zkDocuments/status, and 8.1 says that is fine: "The fourth rule
// regarding sorting of map keys is not required." A test demanding one order
// would be inventing a requirement and would fail against any conformant peer
// that chose differently.
func TestMultipazZkDeviceResponseRoundTrips(t *testing.T) {
	raw, err := os.ReadFile(multipazVector)
	require.NoError(t, err)

	var decoded DeviceResponse
	require.NoError(t, Unmarshal(raw, &decoded))

	reEncoded, err := decoded.Encode()
	require.NoError(t, err)
	require.Len(t, reEncoded, len(raw),
		"same members and values reordered: a length change means something was added or dropped")

	var reDecoded DeviceResponse
	require.NoError(t, Unmarshal(reEncoded, &reDecoded))

	require.Equal(t, decoded.Version, reDecoded.Version)
	require.Equal(t, decoded.Status, reDecoded.Status)
	require.Len(t, reDecoded.ZkDocuments, len(decoded.ZkDocuments))
	require.Equal(t, decoded.ZkDocuments[0].Proof, reDecoded.ZkDocuments[0].Proof,
		"the proof is an opaque bstr and must survive a round trip unchanged")
	require.Equal(t, decoded.ZkDocuments[0].DocumentData, reDecoded.ZkDocuments[0].DocumentData)
}

// TestMultipazZkDocumentDataBytesArePreserved: a zkDocumentData that arrived is
// re-emitted byte for byte, not rebuilt from the struct it decoded into.
//
// 8.1: "Because canonical map ordering is not required, all CBOR maps that are
// used in a cryptographic operation are communicated in a tagged CBOR bytestring.
// For any cryptographic operation, an mdoc, mdoc reader or issuing authority
// infrastructure shall use these bytestrings AS THEY WERE SENT OR RECEIVED,
// without attempting to re-create them from the underlying maps."
//
// Multipaz's bytes are the right ones to assert this on. A fixture this package
// produced would pass whether or not the rule were implemented, because our
// encoder would rebuild what our encoder wrote; these arrived from a different
// implementation with its own key ordering, so only preservation can reproduce
// them.
//
// This test spent its first life recording the opposite as a known gap —
// UnmarshalCBOR discarded the received bytes and MarshalCBOR rebuilt them. The
// harm was latent rather than immediate: longfellow's verifier takes individual
// RequestedAttribute values rather than hashing this blob, so nothing in the
// current AV flow noticed. What it did break is forwarding — a wallet that
// received a ZkDocument and passed it on rewrote bytes it was told to pass
// through, and any future verifier that does hash the wrapper would have
// computed a digest over something the sender never sent.
func TestMultipazZkDocumentDataBytesArePreserved(t *testing.T) {
	raw, err := os.ReadFile(multipazVector)
	require.NoError(t, err)

	var decoded DeviceResponse
	require.NoError(t, Unmarshal(raw, &decoded))

	reEncoded, err := decoded.Encode()
	require.NoError(t, err)

	require.Equal(t, zkDocumentDataBytes(t, raw), zkDocumentDataBytes(t, reEncoded),
		"8.1: the tagged bytestring must be used as it was received")
}

// TestZkDocumentDataRebuiltDropsThePreservedBytes is the escape hatch, and the
// reason it has to exist: preserved bytes mean a decoded value ignores changes
// to its own fields when it re-encodes. Rebuilt makes the fields authoritative
// again, so that behaviour is something a caller opts out of rather than
// discovers.
func TestZkDocumentDataRebuiltDropsThePreservedBytes(t *testing.T) {
	raw, err := os.ReadFile(multipazVector)
	require.NoError(t, err)

	var decoded DeviceResponse
	require.NoError(t, Unmarshal(raw, &decoded))
	data := decoded.ZkDocuments[0].DocumentData

	// Mutating a decoded value changes nothing: the received bytes still win.
	mutated := data
	mutated.DocType = "com.example.something.else"
	asReceived, err := mutated.MarshalCBOR()
	require.NoError(t, err)

	original, err := data.MarshalCBOR()
	require.NoError(t, err)
	require.Equal(t, original, asReceived,
		"a decoded document re-encodes to what it was, whatever its fields now say")

	// Rebuilt hands authority back to the fields.
	rebuilt, err := mutated.Rebuilt().MarshalCBOR()
	require.NoError(t, err)
	require.NotEqual(t, original, rebuilt)

	var check ZkDocumentData
	require.NoError(t, check.UnmarshalCBOR(rebuilt))
	require.Equal(t, "com.example.something.else", check.DocType)
}

// zkDocumentDataBytes digs the Tag-24 zkDocumentData payload out of an encoded
// DeviceResponse without going through ZkDocument, which is the type under test.
func zkDocumentDataBytes(t *testing.T, encoded []byte) []byte {
	t.Helper()

	var envelope struct {
		ZkDocuments []zkDocumentWire `cbor:"zkDocuments"`
	}
	require.NoError(t, Unmarshal(encoded, &envelope))
	require.Len(t, envelope.ZkDocuments, 1)

	payload, err := tag24Unwrap[cbor.RawMessage](envelope.ZkDocuments[0].DocumentData)
	require.NoError(t, err)
	return payload
}
