package sessiontest

import (
	"context"
	"encoding/json"
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/privacybydesign/gabi/signed"
	"github.com/privacybydesign/irmago/client"
	"github.com/privacybydesign/irmago/client/clientsettings"
	"github.com/privacybydesign/irmago/common/clientmodels"
	"github.com/privacybydesign/irmago/internal/common"
	"github.com/privacybydesign/irmago/internal/test"
	"github.com/privacybydesign/irmago/internal/testkeyshare"
	"github.com/privacybydesign/irmago/irma"
	"github.com/privacybydesign/irmago/irma/irmaclient"
	"github.com/privacybydesign/irmago/irma/server/keyshare/keyshareserver" // for MemoryDB
	"github.com/privacybydesign/irmago/testdata"
	"github.com/stretchr/testify/require"
)

const storageRegressionFixtureDir = "storage_regression"

// TestClientStorageRegression loads previously generated client storage databases and verifies
// that all credentials and logs are still available, and that the client can still perform
// IRMA and OpenID4VP sessions, including sessions that require keyshare authentication.
//
// The fixtures are expected at testdata/storage_regression/v<version>/ directories,
// generated by TestGenerateClientStorageForRegressionTests.
func TestClientStorageRegression(t *testing.T) {
	testdataPath := test.FindTestdataFolder(t)
	fixtureDir := filepath.Join(testdataPath, storageRegressionFixtureDir)

	// Find all version subdirectories (v0.19.2, v0.20.0, etc.)
	entries, err := os.ReadDir(fixtureDir)
	if os.IsNotExist(err) {
		t.Skipf("Fixture directory not found at %s; run TestGenerateClientStorageForRegressionTests first", fixtureDir)
	}
	require.NoError(t, err)

	var versionDirs []string
	for _, entry := range entries {
		if entry.IsDir() && strings.HasPrefix(entry.Name(), "v") {
			versionDirs = append(versionDirs, entry.Name())
		}
	}
	if len(versionDirs) == 0 {
		t.Skipf("No version directories found in %s; run TestGenerateClientStorageForRegressionTests first", fixtureDir)
	}

	// Start infrastructure once, shared across subtests
	conf := irmaServerConfWithSdJwtEnabled(t)
	irmaServer := StartIrmaServer(t, conf)
	defer irmaServer.Stop()

	// Start keyshare server and pre-load the saved user databases from all
	// version directories so loaded clients' enrollments are recognized.
	keyshareServer := testkeyshare.StartKeyshareServerWithDB(t, logger, irma.NewSchemeManagerIdentifier("test"), 0)
	defer keyshareServer.Stop()
	for _, versionDir := range versionDirs {
		loadKeyshareUsersFromFixture(t, keyshareServer.DB, filepath.Join(fixtureDir, versionDir))
	}

	for _, versionDir := range versionDirs {
		t.Run(versionDir, func(t *testing.T) {
			versionPath := filepath.Join(fixtureDir, versionDir)

			// --- Phase 1: Load fixture and verify stored state ---
			c, sessionHandler := loadClientFromFixture(t, filepath.Join(versionPath, "bbolt_client_db"))
			defer c.Close()

			creds, err := c.GetCredentials()
			require.NoError(t, err)

			t.Logf("Loaded %d credentials from %s", len(creds), versionDir)
			for _, cred := range creds {
				t.Logf("  - %s", cred.CredentialId)
			}

			requireCredentialPresent(t, creds, "irma-demo.MijnOverheid.fullName")
			requireCredentialPresent(t, creds, "irma-demo.MijnOverheid.singleton")
			requireCredentialPresent(t, creds, "test.test.email")

			// Verify the email credential has SD-JWT instances remaining (10 issued - 2 OpenID4VP disclosures = 8)
			emailCred := findCredentialById(creds, "test.test.email")
			require.NotNil(t, emailCred)
			sdJwtCount := emailCred.BatchInstanceCountsRemaining[clientmodels.CredentialFormat(clientmodels.Format_SdJwtVc)]
			require.NotNil(t, sdJwtCount)
			require.Equal(t, uint(8), *sdJwtCount)

			// Verify logs
			logs, err := c.LoadNewestLogs(100)
			require.NoError(t, err)
			t.Logf("Loaded %d log entries from %s", len(logs), versionDir)
			for _, log := range logs {
				t.Logf("  - type=%s", log.Type)
			}

			require.GreaterOrEqual(t, len(logs), 8, "expected at least 8 log entries")

			requireLogTypePresent(t, logs, clientmodels.LogType_Issuance)
			requireLogTypePresent(t, logs, clientmodels.LogType_Disclosure)
			requireLogTypePresent(t, logs, clientmodels.LogType_Signature)

			openid4vpDisclosureCount := 0
			for _, log := range logs {
				if log.Type == clientmodels.LogType_Disclosure && log.DisclosureLog != nil && log.DisclosureLog.Protocol == clientmodels.Protocol_OpenID4VP {
					openid4vpDisclosureCount++
				}
			}
			require.Equal(t, 2, openid4vpDisclosureCount, "expected 2 OpenID4VP disclosure logs")

			irmaDisclosureCount := 0
			for _, log := range logs {
				if log.Type == clientmodels.LogType_Disclosure && log.DisclosureLog != nil && log.DisclosureLog.Protocol == clientmodels.Protocol_Irma {
					irmaDisclosureCount++
				}
			}
			require.Equal(t, 1, irmaDisclosureCount, "expected 1 IRMA disclosure log")

			// --- Phase 2: Test all session types with loaded client ---
			// Non-keyshare IRMA disclosure
			performDisclosureSessionForAttribute(t, c, sessionHandler, irmaServer, "irma-demo.MijnOverheid.fullName.familyname")
			// Keyshare-protected IRMA disclosure (distributed scheme, requires PIN)
			performKeyshareDisclosureSession(t, c, sessionHandler, irmaServer, "test.test.email.email")
			// OpenID4VP disclosure
			discloseOverOpenID4VP(t, c, sessionHandler, testdata.OpenID4VP_DirectPost_Host)
		})
	}
}

// loadClientFromFixture creates a client.Client from a saved db2 file.
func loadClientFromFixture(t *testing.T, db2Path string) (*client.Client, *MockSessionHandler) {
	var aesKey [32]byte
	copy(aesKey[:], "asdfasdfasdfasdfasdfasdfasdfasdf")

	testdataPath := test.FindTestdataFolder(t)
	storageFolder := test.CreateTestStorage(t)
	storagePath := filepath.Join(storageFolder, "client")

	require.NoError(t, common.CopyDirectory(filepath.Join(testdataPath, "irma_configuration"), filepath.Join(storagePath, "irma_configuration")))
	require.NoError(t, common.CopyDirectory(filepath.Join(testdataPath, "eudi_configuration"), filepath.Join(storagePath, "eudi")))

	certsPath := filepath.Join(storagePath, "eudi", "issuers", "certs")
	require.NoError(t, common.EnsureDirectoryExists(certsPath))
	require.NoError(t, common.SaveFile(filepath.Join(certsPath, "issuer_cert_openid4vc_staging_yivi_app.pem"), testdata.IssuerCert_openid4vc_staging_yivi_app_Bytes))

	// Copy the saved db2 into the storage path (always as "db2", which is what the client expects)
	copyFile(t, db2Path, filepath.Join(storagePath, "db2"))

	// Load the signer key from the fixture
	signer := loadSignerFromFixture(t, filepath.Dir(db2Path))

	irmaConfigurationPath := filepath.Join(storagePath, "irma_configuration")
	eudiAppDataPath := filepath.Join(storagePath, "eudi")
	clientHandler := irmaclient.NewMockClientHandler()
	sessionHandler := &MockSessionHandler{
		SessionChan: make(chan clientmodels.SessionState, 10),
	}
	c, err := client.New(storagePath, irmaConfigurationPath, eudiAppDataPath, clientHandler, sessionHandler, signer, aesKey)
	require.NoError(t, err)

	c.SetPreferences(clientsettings.Preferences{DeveloperMode: true})

	return c, sessionHandler
}

func loadSignerFromFixture(t *testing.T, fixtureDir string) irmaclient.Signer {
	pemPath := filepath.Join(fixtureDir, "ecdsa_sk.pem")
	bts, err := os.ReadFile(pemPath)
	if os.IsNotExist(err) {
		t.Log("No ecdsa_sk.pem in fixture, generating fresh signer")
		return test.NewSigner(t)
	}
	require.NoError(t, err)
	sk, err := signed.UnmarshalPemPrivateKey(bts)
	require.NoError(t, err)
	return test.LoadSigner(t, sk)
}

// performDisclosureSessionForAttribute performs an IRMA disclosure of a non-keyshare attribute.
func performDisclosureSessionForAttribute(t *testing.T, c *client.Client, sessionHandler *MockSessionHandler, irmaServer *IrmaServer, attribute string) {
	req := irma.NewDisclosureRequest()
	req.Disclose = irma.AttributeConDisCon{
		irma.AttributeDisCon{
			irma.AttributeCon{
				irma.NewAttributeRequest(attribute),
			},
		},
	}
	c.NewSession(startSameDeviceIrmaSessionAtServer(t, irmaServer, req))
	session := awaitSessionState(t, sessionHandler)
	require.Equal(t, clientmodels.Status_RequestPermission, session.Status)

	cred := session.DisclosurePlan.DisclosureChoicesOverview[0].OwnedOptions[0]
	grantPermission(t, c, session.Id, makeDisclosureChoice(cred, attribute[strings.LastIndex(attribute, ".")+1:]))

	session = awaitSessionState(t, sessionHandler)
	require.Equal(t, clientmodels.Status_Success, session.Status)
}

// performKeyshareDisclosureSession performs an IRMA disclosure of a keyshare-protected attribute.
// The reloaded client doesn't have the keyshare auth token cached, so a PIN is requested.
func performKeyshareDisclosureSession(t *testing.T, c *client.Client, sessionHandler *MockSessionHandler, irmaServer *IrmaServer, attribute string) {
	req := irma.NewDisclosureRequest()
	req.Disclose = irma.AttributeConDisCon{
		irma.AttributeDisCon{
			irma.AttributeCon{
				irma.NewAttributeRequest(attribute),
			},
		},
	}
	c.NewSession(startSameDeviceIrmaSessionAtServer(t, irmaServer, req))
	session := awaitSessionState(t, sessionHandler)
	require.Equal(t, clientmodels.Status_RequestPermission, session.Status)

	cred := session.DisclosurePlan.DisclosureChoicesOverview[0].OwnedOptions[0]
	grantPermission(t, c, session.Id, makeDisclosureChoice(cred, attribute[strings.LastIndex(attribute, ".")+1:]))

	// The reloaded client needs to authenticate with the keyshare server.
	session = awaitSessionState(t, sessionHandler)
	require.Equal(t, clientmodels.Status_RequestPin, session.Status)

	userInteraction(t, c, clientmodels.SessionUserInteraction{
		SessionId: session.Id,
		Type:      clientmodels.UI_EnteredPin,
		Payload:   clientmodels.PinInteractionPayload{Pin: "12345", Proceed: true},
	})

	session = awaitSessionState(t, sessionHandler)
	require.Equal(t, clientmodels.Status_Success, session.Status)
}

func requireCredentialPresent(t *testing.T, creds []*clientmodels.Credential, credType string) {
	t.Helper()
	cred := findCredentialById(creds, credType)
	require.NotNilf(t, cred, "expected credential %s", credType)
}

func loadKeyshareUsersFromFixture(t *testing.T, db *keyshareserver.MemoryDB, fixtureDir string) {
	bts, err := os.ReadFile(filepath.Join(fixtureDir, "keyshare_users.json"))
	if os.IsNotExist(err) {
		t.Log("No keyshare_users.json in fixture, skipping keyshare user preload")
		return
	}
	require.NoError(t, err)

	var users []keyshareserver.User
	require.NoError(t, json.Unmarshal(bts, &users))

	for i := range users {
		_ = db.AddUser(context.Background(), &users[i])
	}
	t.Logf("Loaded %d keyshare users from fixture", len(users))
}

func requireLogTypePresent(t *testing.T, logs []clientmodels.LogInfo, logType clientmodels.LogType) {
	t.Helper()
	for _, log := range logs {
		if log.Type == logType {
			return
		}
	}
	require.Failf(t, "log type not found", "expected log type %s", logType)
}
