package sessiontest

import (
	"context"
	"encoding/json"
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/privacybydesign/gabi/signed"
	irma "github.com/privacybydesign/irmago"
	"github.com/privacybydesign/irmago/internal/common"
	"github.com/privacybydesign/irmago/internal/test"
	"github.com/privacybydesign/irmago/internal/testkeyshare"
	"github.com/privacybydesign/irmago/irmaclient"
	"github.com/privacybydesign/irmago/server/keyshare/keyshareserver"
	"github.com/privacybydesign/irmago/testdata"
	"github.com/stretchr/testify/require"
)

const storageRegressionFixtureDir = "storage_regression"

// TestClientStorageRegression loads previously generated client storage databases and verifies
// that all credentials and logs are still available, and that the client can still perform
// IRMA and OpenID4VP sessions, including sessions that require keyshare authentication.
//
// The fixtures are expected at testdata/storage_regression/ as bbolt_client_db_v<version> files,
// generated by TestGenerateClientStorageForRegressionTests.
func TestClientStorageRegression(t *testing.T) {
	testdataPath := test.FindTestdataFolder(t)
	fixtureDir := filepath.Join(testdataPath, storageRegressionFixtureDir)

	// Find all version subdirectories (v0.19.2, v0.20.0, etc.)
	entries, err := os.ReadDir(fixtureDir)
	if os.IsNotExist(err) {
		t.Skipf("Fixture directory not found at %s; run TestGenerateClientStorageForRegressionTests first", fixtureDir)
	}
	require.NoError(t, err)

	var versionDirs []string
	for _, entry := range entries {
		if entry.IsDir() && strings.HasPrefix(entry.Name(), "v") {
			versionDirs = append(versionDirs, entry.Name())
		}
	}
	if len(versionDirs) == 0 {
		t.Skipf("No version directories found in %s; run TestGenerateClientStorageForRegressionTests first", fixtureDir)
	}

	// Start infrastructure once, shared across subtests
	conf := irmaServerConfWithSdJwtEnabled(t)
	irmaServer := StartIrmaServer(t, conf)
	defer irmaServer.Stop()

	// Start keyshare server and pre-load the saved user databases from all
	// version directories so loaded clients' enrollments are recognized.
	keyshareServer := testkeyshare.StartKeyshareServerWithDB(t, logger, irma.NewSchemeManagerIdentifier("test"), 0)
	defer keyshareServer.Stop()
	for _, versionDir := range versionDirs {
		loadKeyshareUsersFromFixture(t, keyshareServer.DB, filepath.Join(fixtureDir, versionDir))
	}

	for _, versionDir := range versionDirs {
		t.Run(versionDir, func(t *testing.T) {
			versionPath := filepath.Join(fixtureDir, versionDir)

			// --- Phase 1: Load fixture and verify stored state ---
			client, _ := loadClientFromFixture(t, filepath.Join(versionPath, "bbolt_client_db"))
			defer client.Close()

			credentialInfoList := client.CredentialInfoList()

			t.Logf("Loaded %d credentials from %s", len(credentialInfoList), versionDir)
			for _, cred := range credentialInfoList {
				t.Logf("  - %s (format: %s, hash: %s)", cred.Identifier(), cred.CredentialFormat, cred.Hash)
			}

			requireCredentialPresent(t, credentialInfoList, "irma-demo.MijnOverheid.fullName", irmaclient.Format_Idemix)
			requireCredentialPresent(t, credentialInfoList, "irma-demo.MijnOverheid.singleton", irmaclient.Format_Idemix)
			requireCredentialPresent(t, credentialInfoList, "test.test.email", irmaclient.Format_Idemix)
			requireCredentialPresent(t, credentialInfoList, "test.test.email", irmaclient.Format_SdJwtVc)

			// Verify the SD-JWT email credential has remaining instances (10 issued - 2 OpenID4VP disclosures = 8)
			emailSdJwt := findCredential(credentialInfoList, "test.test.email", irmaclient.Format_SdJwtVc)
			require.NotNil(t, emailSdJwt.InstanceCount)
			require.Equal(t, uint(8), *emailSdJwt.InstanceCount)

			// Verify logs
			logs, err := client.LoadNewestLogs(100)
			require.NoError(t, err)
			t.Logf("Loaded %d log entries from %s", len(logs), versionDir)
			for _, log := range logs {
				t.Logf("  - type=%s", log.Type)
			}

			require.GreaterOrEqual(t, len(logs), 8, "expected at least 8 log entries")

			requireLogTypePresent(t, logs, irmaclient.LogType_Issuance)
			requireLogTypePresent(t, logs, irmaclient.LogType_Disclosure)
			requireLogTypePresent(t, logs, irmaclient.LogType_Signature)

			openid4vpDisclosureCount := 0
			for _, log := range logs {
				if log.Type == irmaclient.LogType_Disclosure && log.DisclosureLog != nil && log.DisclosureLog.Protocol == irmaclient.Protocol_OpenID4VP {
					openid4vpDisclosureCount++
				}
			}
			require.Equal(t, 2, openid4vpDisclosureCount, "expected 2 OpenID4VP disclosure logs")

			irmaDisclosureCount := 0
			for _, log := range logs {
				if log.Type == irmaclient.LogType_Disclosure && log.DisclosureLog != nil && log.DisclosureLog.Protocol == irmaclient.Protocol_Irma {
					irmaDisclosureCount++
				}
			}
			require.Equal(t, 1, irmaDisclosureCount, "expected 1 IRMA disclosure log")

			// --- Phase 2: Test all session types with loaded client ---
			// Non-keyshare IRMA disclosure
			performIrmaDisclosureSessionForAttribute(t, client, irmaServer, "irma-demo.MijnOverheid.fullName.familyname")
			// Keyshare-protected IRMA disclosure (distributed scheme)
			performKeyshareDisclosureSession(t, client, irmaServer, "test.test.email.email")
			// OpenID4VP disclosure
			discloseOverOpenID4VP(t, client, testdata.OpenID4VP_DirectPost_Host)
		})
	}
}

// loadClientFromFixture creates a Client from a saved db2 file.
func loadClientFromFixture(t *testing.T, db2Path string) (*irmaclient.Client, *irmaclient.MockClientHandler) {
	var aesKey [32]byte
	copy(aesKey[:], "asdfasdfasdfasdfasdfasdfasdfasdf")

	testdataPath := test.FindTestdataFolder(t)
	storageFolder := test.CreateTestStorage(t)
	storagePath := filepath.Join(storageFolder, "client")

	require.NoError(t, common.CopyDirectory(filepath.Join(testdataPath, "irma_configuration"), filepath.Join(storagePath, "irma_configuration")))
	require.NoError(t, common.CopyDirectory(filepath.Join(testdataPath, "eudi_configuration"), filepath.Join(storagePath, "eudi_configuration")))

	certsPath := filepath.Join(storagePath, "eudi_configuration", "issuers", "certs")
	require.NoError(t, common.EnsureDirectoryExists(certsPath))
	require.NoError(t, common.SaveFile(filepath.Join(certsPath, "issuer_cert_openid4vc_staging_yivi_app.pem"), testdata.IssuerCert_openid4vc_staging_yivi_app_Bytes))

	copyFile(t, db2Path, filepath.Join(storagePath, "db2"))

	signer := loadSignerFromFixture(t, filepath.Dir(db2Path))

	irmaConfigurationPath := filepath.Join(storagePath, "irma_configuration")
	clientHandler := irmaclient.NewMockClientHandler()
	client, err := irmaclient.New(storagePath, irmaConfigurationPath, clientHandler, signer, aesKey)
	require.NoError(t, err)

	client.SetPreferences(irmaclient.Preferences{DeveloperMode: true})

	return client, clientHandler
}

func loadSignerFromFixture(t *testing.T, fixtureDir string) irmaclient.Signer {
	pemPath := filepath.Join(fixtureDir, "ecdsa_sk.pem")
	bts, err := os.ReadFile(pemPath)
	if os.IsNotExist(err) {
		t.Log("No ecdsa_sk.pem in fixture, generating fresh signer")
		return test.NewSigner(t)
	}
	require.NoError(t, err)
	sk, err := signed.UnmarshalPemPrivateKey(bts)
	require.NoError(t, err)
	return test.LoadSigner(t, sk)
}

func requireCredentialPresent(t *testing.T, creds irma.CredentialInfoList, credType string, format irmaclient.CredentialFormat) {
	t.Helper()
	cred := findCredential(creds, credType, format)
	require.NotNilf(t, cred, "expected credential %s with format %s", credType, format)
}

func findCredential(creds irma.CredentialInfoList, credType string, format irmaclient.CredentialFormat) *irma.CredentialInfo {
	for _, cred := range creds {
		if cred.Identifier() == irma.NewCredentialTypeIdentifier(credType) &&
			irmaclient.CredentialFormat(cred.CredentialFormat) == format {
			return cred
		}
	}
	return nil
}

func performIrmaDisclosureSessionForAttribute(t *testing.T, client *irmaclient.Client, irmaServer *IrmaServer, attribute string) {
	req := irma.NewDisclosureRequest()
	req.Disclose = irma.AttributeConDisCon{
		irma.AttributeDisCon{
			irma.AttributeCon{
				irma.NewAttributeRequest(attribute),
			},
		},
	}
	sessionReqJson := startIrmaSessionAtServer(t, irmaServer, req)
	sessionHandler := irmaclient.NewMockSessionHandler(t)
	client.NewSession(sessionReqJson, sessionHandler)

	permissionRequest := sessionHandler.AwaitPermissionRequest()
	permissionRequest.PermissionHandler(true, &irma.DisclosureChoice{
		Attributes: [][]*irma.AttributeIdentifier{
			{permissionRequest.Candidates[0][0][0].AttributeIdentifier},
		},
	})
	require.True(t, sessionHandler.AwaitSessionEnd())
}

// performKeyshareDisclosureSession performs an IRMA disclosure of a keyshare-protected attribute.
// Unlike performIrmaDisclosureSessionForAttribute, this handles the PIN request that occurs
// when the client's keyshare auth token is not cached (e.g. after reloading from disk).
func performKeyshareDisclosureSession(t *testing.T, client *irmaclient.Client, irmaServer *IrmaServer, attribute string) {
	req := irma.NewDisclosureRequest()
	req.Disclose = irma.AttributeConDisCon{
		irma.AttributeDisCon{
			irma.AttributeCon{
				irma.NewAttributeRequest(attribute),
			},
		},
	}
	sessionReqJson := startIrmaSessionAtServer(t, irmaServer, req)
	sessionHandler := irmaclient.NewMockSessionHandler(t)
	client.NewSession(sessionReqJson, sessionHandler)

	permissionRequest := sessionHandler.AwaitPermissionRequest()

	// Grant permission asynchronously: the permission callback invokes doSession which
	// blocks inside newKeyshareSession waiting for PIN authentication. We need to be able
	// to read the PIN request from the channel while doSession is running.
	go permissionRequest.PermissionHandler(true, &irma.DisclosureChoice{
		Attributes: [][]*irma.AttributeIdentifier{
			{permissionRequest.Candidates[0][0][0].AttributeIdentifier},
		},
	})

	// After permission, the keyshare session authenticates with the server.
	// The reloaded client doesn't have the auth token cached, so a PIN is requested.
	pinHandler := sessionHandler.AwaitPinRequest()
	pinHandler(true, "12345")

	require.True(t, sessionHandler.AwaitSessionEnd())
}

func loadKeyshareUsersFromFixture(t *testing.T, db *keyshareserver.MemoryDB, fixtureDir string) {
	bts, err := os.ReadFile(filepath.Join(fixtureDir, "keyshare_users.json"))
	if os.IsNotExist(err) {
		t.Log("No keyshare_users.json in fixture, skipping keyshare user preload")
		return
	}
	require.NoError(t, err)

	var users []keyshareserver.User
	require.NoError(t, json.Unmarshal(bts, &users))

	for i := range users {
		_ = db.AddUser(context.Background(), &users[i])
	}
	t.Logf("Loaded %d keyshare users from fixture", len(users))
}

func requireLogTypePresent(t *testing.T, logs []irmaclient.LogInfo, logType irmaclient.LogType) {
	t.Helper()
	for _, log := range logs {
		if log.Type == logType {
			return
		}
	}
	require.Failf(t, "log type not found", "expected log type %s", logType)
}
